### ISSUE TITLE
Problems with pip install

### ISSUE THREAD

**Issue by gillibrandpa** [wwaites/saved_fisdat#10]
env) philip.gillibrand@marineharvest.net:saved_fisdat$ python --version
Python 3.6.8

(env) philip.gillibrand@marineharvest.net:saved_fisdat$ pip install --editable .
Obtaining file:///home/philip.gillibrand%40marineharvest.net/work/SAVED/saved_fisdat
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/philip.gillibrand@marineharvest.net/work/SAVED/env/bin/python /home/philip.gillibrand@marineharvest.net/work/SAVED/env/lib64/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ktl_3nfo/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools setuptools-scm 'versioneer[toml]==0.29'
       cwd: None
  Complete output (6 lines):
  Collecting setuptools
    Using cached setuptools-59.6.0-py3-none-any.whl (952 kB)
  Collecting setuptools-scm
    Using cached setuptools_scm-6.4.2-py3-none-any.whl (37 kB)
  ERROR: Could not find a version that satisfies the requirement versioneer[toml]==0.29 (from versions: 0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22)
  ERROR: No matching distribution found for versioneer[toml]==0.29
  ----------------------------------------
WARNING: Discarding file:///home/philip.gillibrand%40marineharvest.net/work/SAVED/saved_fisdat. Command errored out with exit status 1: /home/philip.gillibrand@marineharvest.net/work/SAVED/env/bin/python /home/philip.gillibrand@marineharvest.net/work/SAVED/env/lib64/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ktl_3nfo/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools setuptools-scm 'versioneer[toml]==0.29' Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/philip.gillibrand@marineharvest.net/work/SAVED/env/bin/python /home/philip.gillibrand@marineharvest.net/work/SAVED/env/lib64/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ktl_3nfo/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools setuptools-scm 'versioneer[toml]==0.29' Check the logs for full command output.
(env) philip.gillibrand@marineharvest.net:saved_fisdat$ 

Is there a version requirement on the python environment installation?

**Comment by gillibrandpa** [comment]
I get different errors when I use python 3.11.5 on my workstation at home. Those errors occur when I try to run fisdat. Will try and remember to post this evening.

**Comment by Boorhin** [comment]
Hi,
The dev should correct me if I am wrong but it seems you use a cached setuptool and there is a restriction on versioneer. I am not too sure what is the need for it but if you remove the 
`requires = ["setuptools", "setuptools-scm", "versioneer[toml]==0.29"]`
and replaces by 
`requires = ["setuptools", "setuptools-scm", "versioneer"]`
It will install 0.22 and most likely work. Not too sure what is the point of using **versioneer**, it seems very dev oriented and not maintained.
Other option is to first do `pip install --upgrade setuptools` and `pip install --upgrade setuptools-scm`. This may allow you to use versioneer 0.29 and fulfill the required dependencies. 
Maybe a clear requirement.txt would allow pip to work this out itself.
Good luck!

**Comment by druimalban** [comment]
Hi,

The point of adding it was to have semantic versioning - specifically, it will print the version / commit when the program runs, since we have had trouble with all the Python versions and pip install &c.

It seems brittle and unhelpful, so maybe we remove it.

Worth chatting about this at the meeting tomorrow.

Cheers.

**Comment by gillibrandpa** [comment]
Thanks, I'll give that a go.

**Comment by gillibrandpa** [comment]
No joy I'm afraid:

(env) philip.gillibrand@marineharvest.net:saved_fisdat$ pip --version
pip 21.3.1 from /home/philip.gillibrand@marineharvest.net/work/SAVED/env/lib64/python3.6/site-packages/pip (python 3.6)

(env) philip.gillibrand@marineharvest.net:saved_fisdat$ pip install --editable .
Obtaining file:///home/philip.gillibrand%40marineharvest.net/work/SAVED/saved_fisdat
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/philip.gillibrand@marineharvest.net/work/SAVED/env/bin/python /home/philip.gillibrand@marineharvest.net/work/SAVED/env/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpxzc0_18b
       cwd: /home/philip.gillibrand@marineharvest.net/work/SAVED/saved_fisdat
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/home/philip.gillibrand@marineharvest.net/work/SAVED/env/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/philip.gillibrand@marineharvest.net/work/SAVED/env/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/philip.gillibrand@marineharvest.net/work/SAVED/env/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-esz056uq/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 163, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-esz056uq/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-esz056uq/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 4, in <module>
      from versioneer import get_cmdclass, get_versions
  ImportError: cannot import name 'get_cmdclass'
  ----------------------------------------
WARNING: Discarding file:///home/philip.gillibrand%40marineharvest.net/work/SAVED/saved_fisdat. Command errored out with exit status 1: /home/philip.gillibrand@marineharvest.net/work/SAVED/env/bin/python /home/philip.gillibrand@marineharvest.net/work/SAVED/env/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpxzc0_18b Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/philip.gillibrand@marineharvest.net/work/SAVED/env/bin/python /home/philip.gillibrand@marineharvest.net/work/SAVED/env/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpxzc0_18b Check the logs for full command output.
(env) philip.gillibrand@marineharvest.net:saved_fisdat$

**Comment by wwaites** [comment]
FWIW, on a

```
Darwin joshua.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112 arm64
```

running

```
(saved) ww@joshua saved_fisdat % python --version
Python 3.9.6
(saved) ww@joshua saved_fisdat % pip --version
pip 21.2.4 from /Users/ww/src/saved/lib/python3.9/site-packages/pip (python 3.9)
```

I get no errors. This setup pulls in

```
(saved) ww@joshua saved_fisdat % pip freeze | grep versioneer
versioneer==0.29
```

This is running from the latest main branch revision `a4586ed80a499e0ad88e50b43a798e639029aa02` of Tue Apr 23 16:03:53 2024 +0100

**Comment by gillibrandpa** [comment]
The Versioneer

    like a rocketeer, but for versions!
    https://github.com/python-versioneer/python-versioneer
    Brian Warner
    License: Public Domain (Unlicense)
    Compatible with: Python 3.7, 3.8, 3.9, 3.10, 3.11 and pypy3
    Latest Version

No mention of compatability with python 3.6. Need to upgrade.

**Comment by gillibrandpa** [comment]
As of 2nd August 2024:

(env) philip.gillibrand@marineharvest.net:saved_fisdat$ pip install --editable .
Obtaining file:///home/philip.gillibrand%40marineharvest.net/saved_fisdat
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/philip.gillibrand@marineharvest.net/saved_fisdat/env/bin/python /home/philip.gillibrand@marineharvest.net/saved_fisdat/env/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp6rot9vml
       cwd: /home/philip.gillibrand@marineharvest.net/saved_fisdat
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/philip.gillibrand@marineharvest.net/saved_fisdat/env/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/philip.gillibrand@marineharvest.net/saved_fisdat/env/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/philip.gillibrand@marineharvest.net/saved_fisdat/env/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/tmp/pip-build-env-s12n9eth/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 190, in prepare_metadata_for_build_wheel
      assert len(dist_infos) == 1
  AssertionError
  ----------------------------------------
WARNING: Discarding file:///home/philip.gillibrand%40marineharvest.net/saved_fisdat. Command errored out with exit status 1: /home/philip.gillibrand@marineharvest.net/saved_fisdat/env/bin/python /home/philip.gillibrand@marineharvest.net/saved_fisdat/env/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp6rot9vml Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/philip.gillibrand@marineharvest.net/saved_fisdat/env/bin/python /home/philip.gillibrand@marineharvest.net/saved_fisdat/env/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp6rot9vml Check the logs for full command output.
(e

**Comment by gillibrandpa** [comment]
[Uploading saved.log…]()

**Comment by druimalban** [comment]
To summarise the end of the meeting, we removed the versioneer, but it seems that the LinkML doesn't support Python versions before 3.8. So that's a hard requirement, at least for now.
