### ISSUE TITLE
NameError: name '__version__' is not defined

### ISSUE THREAD

**Issue by tomadams-ssf** [wwaites/saved_fisdat#14]
New error arising since pulling code c 05/08/2024.

$ fisdat sentinel_cages_sampling.yaml deployment_2011-10-26_2011-11-01_cage_8.csv manifest_test.yaml    
 
d:\onedrive profiles\tom\onedrive - scottish sea farms\documents\projects\202312_saved\saved_fisdat\data-utilities\fisdat\data_model.py:371: FutureWarning: Possible nested set at position 10
  pattern=re.compile(r'^:?[a-z]+[[a-z]|_|]*$'))
WARNING [2024-08-13 15:50:44,665] [`term.py' `__new__' (l.287)] ``D:\OneDrive Profiles\Tom\OneDrive - Scottish Sea Farms\Documents\projects\202312_SAVED\saved_fisdat\lib\site-packages\linkml_runtime\linkml_model\model\schema\types does not look like a valid URI, trying to serialize this will break.''
WARNING [2024-08-13 15:50:45,293] [`term.py' `__new__' (l.287)] ``D:\OneDrive Profiles\Tom\OneDrive - Scottish Sea Farms\Documents\projects\202312_SAVED\saved_fisdat\lib\site-packages\linkml_runtime\linkml_model\model\schema\types does not look like a valid URI, trying to serialize this will break.''
Traceback (most recent call last):
  File "D:\OneDrive Profiles\Tom\OneDrive - Scottish Sea Farms\Documents\projects\202312_SAVED\saved_fisdat\Scripts\fisdat-script.py", line 33, in <module>
    sys.exit(load_entry_point('fisdat', 'console_scripts', 'fisdat')())
  File "d:\onedrive profiles\tom\onedrive - scottish sea farms\documents\projects\202312_saved\saved_fisdat\data-utilities\fisdat\cmd_dat.py", line 330, in cli
    manifest_wrapper (data           = args.csvfile
  File "d:\onedrive profiles\tom\onedrive - scottish sea farms\documents\projects\202312_saved\saved_fisdat\data-utilities\fisdat\cmd_dat.py", line 259, in manifest_wrapper
    result = append_job_manifest (data           = data
  File "d:\onedrive profiles\tom\onedrive - scottish sea farms\documents\projects\202312_saved\saved_fisdat\data-utilities\fisdat\cmd_dat.py", line 140, in append_job_manifest
    , local_version = __version__
NameError: name '__version__' is not defined

Windows
Python 3.10.9
Pip 22.3.1

**Comment by tomadams-ssf** [comment]
Mirrors error encountered by PG. He recommended checking out an earlier version of the code:

(dated 23 July, commit message "[Echo location of result](https://github.com/saved-models/data-utilities/commit/a70efdba00aaff8dce42f0a698b8f1af572a5b3f)")

**Comment by druimalban** [comment]
I think I've fixed it (https://github.com/saved-models/data-utilities/commit/93ab8c71c3677186c92f5bfa4670da2bbadaabca). It originates from removing the versioneer thing a week or two ago. 

We already depend on setuptools so I'm now using that to get the version number specified in `setup.py`. All the unit tests pass and I successfully uploaded.

You will need to recreate the virtual environment again for this to work as I had to include the dependency on setuptools inside the virtual environment.

**Comment by tomadams-ssf** [comment]
Can confirm that this is now working with latest commit - thank you.
